--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: redis
    component: queue-1
  name: redis
spec: 
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector: 
    app: redis
    component: queue-1

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    component: queue-1
spec:
  selector:
    matchLabels:
      app: redis
      component: queue-1
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        component: queue-1
    spec:
      containers:
      - name: redis
        image: obcontainerregistry.azurecr.io/azure-vote-back:v1
        ports:
        - containerPort: 6379
          name: redis
      imagePullSecrets:
      - name: azure-acr