---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    role: result
    app: node
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 80
      name: result
  selector:
    role: result
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: result
        app: node
    spec:
      containers:
      - name: result
        image: obcontainerregistry.azurecr.io/results:v0.1
        ports:
        - containerPort: 80
          name: result
      imagePullSecrets:
      - name: azure-acr
