--- 
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  labels: 
    app: java
    role: worker
  name: worker
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: worker
    spec: 
      containers: 
        - name: worker
          image: obcontainerregistry.azurecr.io/worker:v0.1
      imagePullSecrets:
      - name: azure-acr
